# Generated by Django 6.0 on 2025-12-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome do Pet / Título')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Foto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Galeria de Fotos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
