# Generated by Django 6.0 on 2025-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
