# Generated by Django 6.0 on 2025-12-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='active',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Ativo'),
        ),
    ]
