# Generated by Django 6.0 on 2025-12-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido?')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
            ],
            options={
                'verbose_name': 'Inscrito na Newsletter',
                'verbose_name_plural': 'Inscritos na Newsletter',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_banner', models.ImageField(upload_to='site_setup/', verbose_name='Banner da Página Inicial')),
                ('about_image', models.ImageField(upload_to='site_setup/', verbose_name='Foto da Seção Sobre Nós')),
                ('contact_banner', models.ImageField(blank=True, null=True, upload_to='site_setup/', verbose_name='Banner da Página de Contato')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
