# Generated by Django 6.0 on 2025-12-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_banner', models.ImageField(upload_to='site_setup/', verbose_name='Banner da Página Inicial')),
                ('about_image', models.ImageField(upload_to='site_setup/', verbose_name='Foto da Seção Sobre Nós')),
                ('contact_banner', models.ImageField(blank=True, null=True, upload_to='site_setup/', verbose_name='Banner da Página de Contato')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
