# Generated by Django 6.0 on 2025-12-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Identificador único para URL (ex: ração-premium)', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (R$)')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional (R$)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto/Serviço',
                'verbose_name_plural': 'Produtos e Serviços',
            },
        ),
    ]
